### ISSUE TITLE
 ERROR #11321  PLUGIN fetcher is not a function

### ISSUE THREAD

**Issue by d-floutier** [wyze/gatsby-source-graphql#22]
ERROR #11321  PLUGIN

"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:

fetcher is not a function

  79 | 
  80 |     if (!sdl) {
> 81 |       introspectionSchema = await introspectSchema(link);
     |                                   ^
  82 |       sdl = printSchema(introspectionSchema);
  83 |     } else {
  84 |       introspectionSchema = buildSchema(sdl);

File: node_modules/gatsby-source-graphql/gatsby-node.js:81:35

  TypeError: fetcher is not a function
  
  - introspectSchema.js:14 introspectSchema
    [vide]/[graphql-tools-fork]/dist/stitch/introspectSchema.js:14:12
  
  - gatsby-node.js:81 Object.exports.sourceNodes
    [vide]/[gatsby-source-graphql]/gatsby-node.js:81:35

**Comment by wyze** [comment]
Hi @d-floutier, you should file an issue with Gatsby as they have a plugin with the same name. This is actually published under `@wyze/gatsby-source-graphql`.
