### ISSUE TITLE
Is this compatible with GatsbyJS v2?

### ISSUE THREAD

**Issue by kishba** [wyze/gatsby-source-graphql#7]
We started a new project with the beta of Gatsby v2, but we're not seeing any nodes get created with this plugin like we did in our GatsbyJS v1 app. Do you know what will need to change with this plugin to work in the next version of Gatsby?

**Comment by kishba** [comment]
Oops! We hadn't included `gatsby-source-filesystem` so our graphql query files weren't being process. Sorry for the mistaken issue!

**Comment by wyze** [comment]
No worries, glad you got it solved relatively quickly!
