### ISSUE TITLE
GraphQL Error Unknown field `viewer` on type `RootQueryType`

### ISSUE THREAD

**Issue by gouravsood** [wyze/gatsby-source-graphql#9]
Hi,

I am trying to setup a sample project to test the GraphQL API Integration based on the steps in README file of this plugin and getting below error:

```
GraphQL Error Unknown field `viewer` on type `RootQueryType`

  file: /Users/dev/gatsby-source-graphql-usage/src/pages/index.js

   1 |
   2 | query RepositoriesQuery {
>  3 |   viewer {
     |   ^
   4 |     repositories(privacy: PUBLIC, affiliations: OWNER, isFork: false, first: 100) {
   5 |       nodes {
   6 |         name
   7 |         url
   8 |       }
   9 |     }
  10 |   }
  11 | }
  12 |
```

You can find the code of this example here:  https://github.com/gouravsood/gatsby-source-graphql-usage 

Can you please help?

**Comment by wyze** [comment]
Hello,

It looks like you are missing the name of the file/node in your query in your index page.

```diff
export const query = graphql`
query RepositoriesQuery {
+ githubGraphQl {
    viewer {
      repositories(privacy: PUBLIC, affiliations: OWNER, isFork: false, first: 100) {
        nodes {
          name
          url
        }
      }
    }
+ }
}
`
```

**Comment by wyze** [comment]
The query will map different from GitHub to what you need to use in Gatsby. One way to visualize this is to comment out the query, so the project will build, and then while running `yarn develop`, you can visit: http://localhost:8000/___graphql and see the queries available there.

I've submitted a pull request, https://github.com/gouravsood/gatsby-source-graphql-usage/pull/1, that will fix the build for you.

**Comment by gouravsood** [comment]
Thanks a lot @wyze for submitting that PR. I have tried running at local and unfortunately I am still getting the same error:

```
GraphQL Error Unknown field `githubGraphQl` on type `RootQueryType`

  file: /Users/gatsby-source-graphql-usage/src/pages/index.js

   1 |
   2 | query RepositoriesQuery {
>  3 |   githubGraphQl {
     |   ^
   4 |     viewer {
   5 |       repositories {
   6 |         nodes {
   7 |           name
   8 |           url
   9 |         }
  10 |       }
  11 |     }
  12 |   }
  13 | }
```

As you suggested, I have commented the query to make build successful and can't see anything in the explorer.

Here is my `gatsby-config.js`, may be I am missing something:
```
// Optionally pull in environment variables
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`,
})

module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'queries',
        path: `${__dirname}/src/queries/`,
      },
    },
    {
      resolve: '@wyze/gatsby-source-graphql',
      options: {
        headers: {
          authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
        },
        url: 'https://api.github.com/graphql',
      },
    },
  ],
}

```

**Comment by wyze** [comment]
It was working when I submitted my PR. I wonder if it is a cache issue. Can you try deleting the `.cache` folder in your project and running it again?

**Comment by gouravsood** [comment]
hmmm that's weird. I have removed both `.cache`, `node_modules` and `public` folder to start from scratch but still the same error :(

```
GraphQL Error Unknown field `githubGraphQl` on type `RootQueryType`

  file: /Users/gatsby-source-graphql-usage/src/pages/index.js

   1 |
   2 | query RepositoriesQuery {
>  3 |   githubGraphQl {
     |   ^
   4 |     viewer {
   5 |       repositories {
   6 |         nodes {
   7 |           name
   8 |           url
   9 |         }
  10 |       }
  11 |     }
  12 |   }
  13 | }
```

**Comment by wyze** [comment]
I wonder if there is something else going on. If you comment out the query, then navigate to http://localhost:8000/___graphql and click Docs, scroll all the way to the bottom and screenshot that.

Here is mine:

![image](https://user-images.githubusercontent.com/186971/44684147-e5b5e500-aa0d-11e8-9c29-8e2d5c5263ce.png)

**Comment by gouravsood** [comment]
I cannot see the githubGraphQl node.

![image](https://user-images.githubusercontent.com/4436378/44684460-7d5a1880-aa8c-11e8-9a6b-b802d217c900.png)

Can it be because of the GITHUB_TOKEN? I have generated token from Settings > Developer Settings > Personal access tokens. Given all the available scopes (for testing), but still no luck.

![image](https://user-images.githubusercontent.com/4436378/44684590-cca04900-aa8c-11e8-9389-7eaa14adf06b.png)

**Comment by wyze** [comment]
If there was an issue with the token, the build would output a message before it tried to build the pages.

Let's try a couple of things, can you do the following and post the results.

- [ ] Run `npx envinfo --preset jest`
- [ ] Run `yarn build > out.log`

**Comment by gouravsood** [comment]
Here are details:

npx envinfo --preset jest

```
gsood:gatsby-source-graphql-usage gsood$ npx envinfo --preset jest

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.6.0 - ~/.yarn/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
```

yarn build > out.log
```
yarn run v1.6.0
$ gatsby build
success delete html and css files from previous builds — 0.011 s
success open and validate gatsby-config — 0.005 s
success copy gatsby files — 0.015 s
success onPreBootstrap — 0.031 s
success source and transform nodes — 0.044 s
success building schema — 0.117 s
success createLayouts — 0.007 s
success createPages — 0.000 s
success createPagesStatefully — 0.012 s
success onPreExtractQueries — 0.000 s
success update schema — 0.063 s
success extract queries from components — 0.032 s
success run graphql queries — 0.021 s
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 2.266 s

success Building CSS — 3.433 s
success Building production JavaScript bundles — 5.577 s
undefined
success Building static HTML for pages — 2.048 s
info Done building in 13.326 sec
Done in 13.49s.

```

**Comment by wyze** [comment]
Super odd. We are on same version of macOS, but your versions of yarn/npm are behind mine a little, nothing that would cause this though.

My next suggestion would be to clone the repo for this plugin, and add some console.log statements to the source, like checking it get's past `node.extension` or what `response` is.

Then you can run `yarn build`, and `yarn link`. Then if you go back to your repo that is having the issue, you can run `yarn link @wyze/gatsby-source-graphql`. Hopefully you see `console.log` statements during the build process and we can track down what is going on.

**Comment by gouravsood** [comment]
Thanks a lot @wyze for the suggestion. I added logs in onCreateNode function and found that the GITHUB token was passed correctly to the plugin. Hence plugin was throwing "Bad Credentials" error during first run. But from second run onwards, plugin was not even trying to connect to GITHUB and my build was getting passed.

That was my silly mistake because I was running the command as `yarn develop GITHUB_TOKEN=<token>`, but it should have been `GITHUB_TOKEN=<token> yarn develop`. After passing the token before the command, all worked and now I can see the node in http://localhost:8000/___graphql  and in the application.

![snapshot](https://user-images.githubusercontent.com/4436378/44746395-9aa2eb80-ab4d-11e8-8a03-d05550ead98b.jpg)

**Comment by wyze** [comment]
Awesome @gouravsood. I'm glad you got it solved!

**Comment by gouravsood** [comment]
Thanks a lot for your help @wyze. I have documented all the details in the readme here https://github.com/gouravsood/gatsby-source-graphql-usage

**Comment by wyze** [comment]
No problem, anytime! Readme looks great as well.
